### ISSUE TITLE
Elastic agent install error

### ISSUE THREAD

**Issue by awnyshaheen** [swimlane/elk-tls-docker#23]
elastic-agent    | /usr/local/lib/python3.8/dist-packages/urllib3/connectionpool.py:1013: InsecureRequestWarning: Unverified HTTPS request is being made to host 'kibana'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/1.26.x/advanced-usage.html#ssl-warnings
elastic-agent    |   warnings.warn(
elastic-agent    | Traceback (most recent call last):
elastic-agent    |   File "/install.py", line 19, in <module>
elastic-agent    |     agent.install(version=os.environ.get('ELK_VERSION'), preflight_check=preflight)
elastic-agent    |   File "/usr/local/lib/python3.8/dist-packages/elastic_agent_setup/elastic_agent.py", line 46, in install
elastic-agent    |     return self.__platform_run('install')
elastic-agent    |   File "/usr/local/lib/python3.8/dist-packages/elastic_agent_setup/elastic_agent.py", line 31, in __platform_run
elastic-agent    |     return Linux().run(subcommand=subcommand)
elastic-agent    |   File "/usr/local/lib/python3.8/dist-packages/elastic_agent_setup/platform/platform.py", line 39, in run
elastic-agent    |     return subprocess.run(command, shell=True, check=True, capture_output=True)
elastic-agent    |   File "/usr/lib/python3.8/subprocess.py", line 516, in run
elastic-agent    |     raise CalledProcessError(retcode, process.args,
elastic-agent    | subprocess.CalledProcessError: Command 'cd /elastic-agent-7.15.0-linux-x86_64 && ./elastic-agent install --force --kibana-url="https://kibana:5601" --enrollment-token="cXNjLV8zd0JBeUdtcFJPMmlqWHQ6SGFrVXd6VVlSaENsTldlNTBxOUJsQQ==" --certificate-authorities="/ca.crt" ' returned non-zero exit status 1.

**Comment by Und3rf10w** [comment]
Are you using a self-signed certificate? If so, add `--insecure` to the elastic-agent command. Also, you may want to view the output of the command, I'd also add `1>/proc/1/fd/1 2>/proc/1/fd/2` so that you can view the logs of the `elastic-agent` with `sudo docker-compose logs --tail 100 elastic-agent`
